### ISSUE TITLE
Not working with mac. It will be helpful i you can make a new one with mac with entirety. but with chatgpt  after lots of try we get {"error":{"code":400,"message":"Parameter request_type is required."}}

### ISSUE THREAD

**Issue by shiva0000000** [theanuragshukla/gfg_potd_solver#2]

**Comment by theanuragshukla** [comment]
Hey, I'll look into the issue ASAP. Till then, try these tips:

- make sure your `decoy_creds.env` and `real_creds.env` are populated correctly
- try running the code in a bash shell, or use a `python venv`
- update the issue with any other relevant information
- do not modify any script files (it seems you did)
- If you changed any files,
 - clone the repo again
 - fill in the creds
 - pip install
 - and then run

**Comment by shiva0000000** [comment]
- i have made  sure decoy_creds.env and real_creds.env are populated correctly.
- also I am using virtual env. only for this project
- --
- i only modified the parts where mac os does not support. like in .sh files. i changed:
  1.  -H 'sec-ch-ua-platform: "Macintosh"'
  2.  -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36') 
  3.  and also grep -P does not work so i gfgSubmit.sh from slug=$(echo "$url" | sed -n 's|.*/problems/\(.*\)/.*|\1|p') to slug=$(echo "$url" | grep -oP '(?<=problems\/).*?(?=\/)')
- now based on this the code is working correctly for gfgPotd.sh,gfgProblems.sh,gfgSolutions.sh as it loads all the correct code in terminal. but ig there is problem in submit coz it is not able to submit the results.
- i have also added the console output for your reference.
- also i would be very happy i u could share you contact and we can have a chat

**Comment by theanuragshukla** [comment]
The curl headers (`-H` ) doesn't matter, Its only there for gfg servers, and won't cause any issues. Looking at the console outputs, there are issues in submit script. I checked it on mac, and it works fine.
Can you try the original submit script but, only change the grep/sed part and not anything else. check if it helps.

- the sed command you mentioned looks faulty, as its missing `-r` which is required for back-referencing(`\1`).

also, don't post raw console outputs on github as it included your auth cookies. make sure to redact sensitive info before posting.

**Comment by shiva0000000** [comment]
First of all thank you for removing my output file.

second i copied back your same gfgSubmit.sh 
and wrote sed part in 3 diff ways:
1. slug=$(echo "$url" | grep -oP '(?<=problems\/).*?(?=\/)')
2. slug=$(echo "$url" | sed -oP '(?<=problems\/).*?(?=\/)')
3. slug=$(echo "$url" | sed -rn 's|./problems/(.)/.|\1|p')
It failed in all the ways. what should i do?

**Comment by theanuragshukla** [comment]
can you provide output for the following command in your terminal: 
```sh
echo "https://www.geeksforgeeks.org/problems/123/1" | grep -oP '(?<=problems\/).*?(?=\/)'
```
this should output: `123`

**Comment by shiva0000000** [comment]
echo "https://www.geeksforgeeks.org/problems/123/1" | grep -oP '(?<=problems\/).*?(?=\/)'. 
with this i got:
grep: invalid option -- P
usage: grep [-abcdDEFGHhIiJLlMmnOopqRSsUVvwXxZz] [-A num] [-B num] [-C[num]]
        [-e pattern] [-f file] [--binary-files=value] [--color=when]
        [--context[=num]] [--directories=action] [--label] [--line-buffered]
        [--null] [pattern] [file ...]

but with this:
echo "https://www.geeksforgeeks.org/problems/123/1" | grep -o 'problems\/[^\/]*'
problems/123

**Comment by theanuragshukla** [comment]
got it. Mac uses BSD version for grep, which doesn't support `-P`. I'll replace all greps with `sed` or `awk`, which is common for both GNU and BSD. I'll push the changes in next commit.

**Comment by theanuragshukla** [comment]
@shiva0000000 fixed in the latest commit
